// <auto-generated />
namespace Lab2_DoGiaLam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BigSchoolProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BigSchoolProject));
        
        string IMigrationMetadata.Id
        {
            get { return "202205300145300_BigSchool Project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
